teacher_tokenizer_name: google/gemma-2-2b-it:source=Gemma2
target_tokenizer_name: Qwen/Qwen2.5-1.5B:source=Qwen2:target=Gemma2
output: outputs/tokenizer_data/gemma2_to_qwen2
seed: 1234
additive_smoothing_constant: 1e-9
teacher_subsample_percent: null
student_subsample_percent: null

data:
  batch_size: 1024
  num_workers: 64

defaults:
  - _self_
  - data: tulu3